version: '3.8'
services:
  database:
    container_name: influxdb
    image: influx_image
    restart: always
    ports:
      - 8086:8086
    build: 
      context: .
      dockerfile: servicios/influx/Dockerfile
    networks:
      default:
        aliases:
          - influxdb

  broker:
    container_name: rabbit
    image: rabbit_image
    restart: always
    ports:
      - 1883:1883
      - 15672:15672
      - 5672:5672
    build: 
      context: .
      dockerfile: servicios/rabbit/Dockerfile
    networks:
      default:
        aliases:
          - rabbit

  visualizador:
    container_name: grafana
    image: grafana_image
    restart: always
    ports:
      
      - 3000:3000
    build: 
      context: .
      dockerfile: servicios/grafana/Dockerfile

  telegraf:
    image: telegraf:1.25.0
    container_name: telegraf
    restart: always
    environment:
      - INFLUX_TOKEN=HgRhfDV_oQlela2hH2oJUazmo1Pxp4Z9XtltWL2zXR0z58dr8TKqrXV24fnNJtECMF7CMuAB3LMVqRlrJJu39w==
    command: --config http://influxdb:8086/api/v2/telegrafs/0aaaecc1421e1000
    depends_on:
      - database     


                    